mybatis:
  type-aliases-package: com.thk.apple.dto
  mapperLocations: classpath:mapping/*.xml
server:
  port: 8080
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/ 
      suffix: .jsp
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://IP:PORT/DB명?useSSL=false&amp;characterEncoding=UTF-8&amp;serverTimezone=UTC
    username: 아이디
    password: 비번
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB      